version: '3.6'

services:
  docker:
    image: docker:dind
    privileged: true
    volumes:
      - .:/codingworkshops/fable
    ports:
      - 2375:2375

  db:
    image: postgres:10.1-alpine

  web:
    build: .
    command: pipenv run /codingworkshops/manage.py migrate
    command: pipenv run /codingworkshops/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/codingworkshops
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY=changemeinprod
    depends_on:
      - db
      - docker
