version: '3.6'

services:
  docker:
    image: docker:dind
    privileged: true
    volumes:
      - ./fable:/fable:ro

  db:
    image: postgres:10.1-alpine

  web:
    build: .
    volumes:
      - ./codingworkshops:/codingworkshops/codingworkshops
      - ./fable:/fable:ro
    ports:
      - 8000:8000
    environment:
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - BUILD_IMAGES=${BUILD_IMAGES}
    depends_on:
      - db
      - docker
