version: '3.6'

services:
  docker:
    image: docker:dind
    privileged: true
    volumes:
      - ./fable:/fable:ro

  db:
    image: postgres:10.1-alpine

  web:
    build: .
    volumes:
      - ./codingworkshops:/codingworkshops/codingworkshops:ro
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY=changemeinprod
    depends_on:
      - db
      - docker
