version: '3.6'

services:
  db:
    image: postgres:10.1-alpine

  web:
    build: .
    command: pipenv run python /codingworkshops/manage.py migrate
    command: pipenv run python /codingworkshops/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/codingworkshops
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY=changemeinprod
    depends_on:
      - db
