# Generated by Django 2.1.1 on 2018-09-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0005_workshop_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direction',
            name='correct_code',
        ),
        migrations.AddField(
            model_name='slide',
            name='starting_code',
            field=models.TextField(default=''),
        ),
    ]
