# Generated by Django 2.1.1 on 2018-09-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0006_auto_20180912_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='hint',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
