# Generated by Django 2.1.1 on 2018-09-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0008_auto_20180919_1952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='slide',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='workshop',
            options={'ordering': ['pk']},
        ),
        migrations.AddField(
            model_name='workshop',
            name='is_draft',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
