# Generated by Django 2.1.1 on 2018-09-24 16:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workshops', '0009_auto_20180923_1747'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direction',
            options={'ordering': ['index']},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['index']},
        ),
        migrations.AlterModelOptions(
            name='slide',
            options={'ordering': ['index']},
        ),
        migrations.AddField(
            model_name='direction',
            name='index',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='index',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slide',
            name='index',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slide',
            name='starting_code',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='workshop',
            unique_together={('author', 'name')},
        ),
    ]
