# Generated by Django 2.1.1 on 2018-09-24 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0010_auto_20180924_1651'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='direction',
            unique_together={('slide', 'index')},
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('workshop', 'index')},
        ),
        migrations.AlterUniqueTogether(
            name='slide',
            unique_together={('lesson', 'index')},
        ),
    ]
