# Generated by Django 2.1.1 on 2018-09-24 22:51

import codingworkshops.workshops.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0011_auto_20180924_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='name',
            field=models.CharField(
                max_length=50,
                validators=[codingworkshops.workshops.models.name_validator]
            ),
        ),
    ]
