# Generated by Django 2.1.1 on 2018-09-25 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0012_auto_20180924_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
