# Generated by Django 2.1.1 on 2018-09-25 01:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0013_auto_20180925_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
