# Generated by Django 2.1.1 on 2018-09-25 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0014_workshop_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
