# Generated by Django 2.1.1 on 2018-10-20 22:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workshops', '0015_auto_20180925_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='contributors',
            field=models.ManyToManyField(related_name='contributed_workshop_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
