# Generated by Django 2.1.1 on 2018-10-24 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0016_workshop_contributors'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='source_url',
            field=models.URLField(blank=True),
        ),
    ]
