# Generated by Django 2.1.1 on 2018-10-20 22:50

import codingworkshops.users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180822_0001'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', codingworkshops.users.models.CustomUserManager()),
            ],
        ),
    ]
